//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokProgrami.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public long id { get; set; }
        public long id_user { get; set; }
        public Nullable<long> id_role { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
