//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokProgrami.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitType
    {
        public long id { get; set; }
        public string name { get; set; }
        public long id_product_type { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
